# Generated by Django 4.2 on 2024-03-27 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('finish', models.DateField(auto_created=True, blank=True, null=True)),
                ('start', models.DateField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('amount', models.IntegerField(blank=True, default=200000, null=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('continuity', models.IntegerField(blank=True, default=1, null=True)),
                ('room_time', models.CharField(blank=True, choices=[('8-00', '10-00'), ('9-00', '11-00'), ('10-00', '12-00'), ('11-00', '13-00'), ('12-00', '14-00'), ('13-00', '15-00'), ('14-00', '16-00'), ('15-00', '17-00'), ('16-00', '18-00')], max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachers.teacher')),
            ],
        ),
    ]
